version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-to-google-tts"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-dl6z30u7pypu"
s3_prefix = "lambda-to-google-tts"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

